# Default build pipeline -- triage, implement, verify, review
#
# Triage is a decision node: it evaluates the ticket and either continues
# to implementation or signals fail/blocked/decompose via a JSON disposition.
#
# Implement and verify are action nodes: they just do work, no output parsing.
#
# Review is a decision node: it evaluates the implementation and either
# continues (succeed) or signals fail.
model: claude-sonnet-4-5-20250929
max_retries: 2
max_depth: 2
discretion: medium

workflows:
  main:
    - name: triage
      type: decision
      prompt: triage.md
    - name: implement
      type: action
      prompt: implement.md
    - name: verify
      type: action
      run: just test
    - name: review
      type: decision
      prompt: review.md

# Commands to run after all nodes succeed (before ticket is closed).
# $TICKET_ID, $CHANGED_FILES, and $KO_TICKET_WORKSPACE are available.
# on_succeed:
#   - git add -A
#   - git commit -m "ko: implement ${TICKET_ID}"

# Commands to run after ticket is closed (safe for deploys).
# on_close:
#   - git push

# Commands to run once after the agent loop completes.
# $LOOP_PROCESSED, $LOOP_SUCCEEDED, $LOOP_FAILED, $LOOP_BLOCKED, $LOOP_DECOMPOSED,
# $LOOP_STOPPED, and $LOOP_RUNTIME_SECONDS are available.
# on_loop_complete:
#   - echo "Loop processed $LOOP_PROCESSED tickets ($LOOP_SUCCEEDED succeeded)"
#   - test $LOOP_SUCCEEDED -gt 0 && git push
